### ISSUE TITLE
Please release the sources of the libraries, or don't claim your appi is open source

### ISSUE THREAD

**Issue by danielegobbetti** [Odoo-mobile/crm#49]
The only open source part of this app (and the framework from the same organization) is the front-end. The logic that connects the app to odoo is (probably, I can't tell since the sources are not available) is held into the odoo-rpc-v2.aar binary file that is added to the project.

For instance if you remove the play services dependency from the gradle file the app builds and installs, but then force closes on account setup on a device without google play services with the error:

```
E/AndroidRuntime(10930): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(10930): Process: com.odoo.crm, PID: 10930
E/AndroidRuntime(10930): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(10930): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(10930): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(10930): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(10930): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(10930): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(10930): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(10930): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(10930): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(10930): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GoogleCloudMessaging;
E/AndroidRuntime(10930): 	at odoo.kernel.DeviceInfo.getGCMKey(DeviceInfo.java:139)
E/AndroidRuntime(10930): 	at odoo.kernel.OdooRegister.register(OdooRegister.java:125)
E/AndroidRuntime(10930): 	at odoo.Odoo.pingDevice(Odoo.java:435)
E/AndroidRuntime(10930): 	at odoo.Odoo.authenticate(Odoo.java:603)
E/AndroidRuntime(10930): 	at com.odoo.core.support.OdooLoginHelper.login(OdooLoginHelper.java:52)
E/AndroidRuntime(10930): 	at com.odoo.core.account.OdooLogin$LoginProcess.doInBackground(OdooLogin.java:353)
E/AndroidRuntime(10930): 	at com.odoo.core.account.OdooLogin$LoginProcess.doInBackground(OdooLogin.java:321)
E/AndroidRuntime(10930): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(10930): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(10930): 	... 4 more
E/AndroidRuntime(10930): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GoogleCloudMessaging" on path: DexPathList[[zip file "/data/app/com.odoo.crm-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(10930): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(10930): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(10930): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(10930): 	... 13 more
E/AndroidRuntime(10930): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.gcm.GoogleCloudMessaging
E/AndroidRuntime(10930): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(10930): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(10930): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(10930): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(10930): 		... 14 more
E/AndroidRuntime(10930): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager(  466):   Force finishing activity 1 com.odoo.crm/com.odoo.core.account.OdooLogin
```
The odoo.Odoo and the odoo.kernel packages are not part of the released sources.
Claiming that this app is open source is bogus.

**Comment by falinwa** [comment]
yes, I agree. I trying to find the code to understand the logic how this app connect to back end, but I can't find it. I think Odoo must open this code.
Thank You.

**Comment by ilexius** [comment]
We are running the framework example on Android M and sync is not working. We are happy to debug and fix this, but can't because the source of odoo-rpc-v3.aar is not public.
Why has this not been released?
